In [1]:
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder

In [2]:
data = pd.read_csv('Churn_Modelling.csv')

In [3]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
data = data.drop(['RowNumber','CustomerId','Surname'], axis=1)

In [5]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [7]:
# Onehot encode Geography
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
# Combine
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [9]:
# Split the features
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo, file)
    
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler, file)

# ANN Regression Problem Statement

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [14]:
# Build our ANN Model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)), #HL1 connected with input layer
    Dense(32, activation='relu'), #HL2
    Dense(1) #output : default linear activation function
])

# compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

c:\Users\Shikhaj Somani\OneDrive\Desktop\ML\Churn Modelling ANN\venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [17]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [19]:
# Training the model
history = model.fit(
    X_train,y_train,
    validation_data = (X_test, y_test),
    epochs=100, 
    callbacks=[tensorboard_callback, early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 100386.9766 - mae: 100386.9766 - val_loss: 98545.3125 - val_mae: 98545.3125
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99689.9922 - mae: 99689.9922 - val_loss: 97120.6562 - val_mae: 97120.6562
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 97164.6016 - mae: 97164.6016 - val_loss: 93423.2891 - val_mae: 93423.2891
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 92174.4062 - mae: 92174.4062 - val_loss: 87219.4922 - val_mae: 87219.4922
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 84809.6250 - mae: 84809.6250 - val_loss: 79040.9531 - val_mae: 79040.9531
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 75953.6016 - mae: 75953.6016 - val_loss: 70265.8984 - val_mae: 70265.8984
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 67170.4531 - mae: 67170.4531 - val_loss: 62542.5781 - val_mae: 62542.5781
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 59908.0508 - mae: 59908.0508 - val_loss: 56795.6992 - val_mae: 56795.6992
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 55002.1719 - mae: 55002.1719 - val_loss: 53266.1445 - val_mae: 53266.1445
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52292.8750 - mae: 52292.8750 - val_loss: 51584.1719 - val_mae: 51584.1719
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51049.2617 - mae: 51049.2617 - val_loss: 50984.2344 - val_mae: 50984.2344
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50562.4961 - mae: 50562.4961 - val_loss: 50783.7891 - val_mae: 50783.7891
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50354.0156 - mae: 50354.0156 - val_loss: 50680.3398 - val_mae: 50680.3398
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50246.7266 - mae: 50246.7266 - val_loss: 50614.6016 - val_mae: 50614.6016
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50179.6328 - mae: 50179.6328 - val_loss: 50555.9492 - val_mae: 50555.9492
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50124.8828 - mae: 50124.8828 - val_loss: 50515.7188 - val_mae: 50515.7188
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50077.8672 - mae: 50077.8672 - val_loss: 50478.1680 - val_mae: 50478.1680
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50040.1016 - mae: 50040.1016 - val_loss: 50442.0859 - val_mae: 50442.0859
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50004.3984 - mae: 50004.3984 - val_loss: 50419.5938 - val_mae: 50419.5938
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49971.8672 - mae: 49971.8672 - val_loss: 50386.6953 - val_mae: 50386.6953
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49939.5234 - mae: 49939.5234 - val_loss: 50363.5898 - val_mae: 50363.5898
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49911.8906 - mae: 49911.8906 - val_loss: 50345.8008 - val_mae: 50345.8008
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49888.0664 - mae: 49888.0664 - val_loss: 50332.8906 - val_mae: 50332.8906
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49861.7422 - mae: 49861.7422 - val_loss: 50318.5586 - val_mae: 50318.5586
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49840.1094 - mae: 49840.1094 - val_loss: 50300.9961 - val_mae: 50300.9961
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49822.3320 - mae: 49822.3320 - val_loss: 50290.6367 - val_mae: 50290.6367
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49798.9766 - mae: 49798.9766 - val_loss: 50280.9062 - val_mae: 50280.9062
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49780.7266 - mae: 49780.7266 - val_loss: 50273.8555 - val_mae: 50273.8555
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49763.9648 - mae: 49763.9648 - val_loss: 50268.9883 - val_mae: 50268.9883
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49746.9336 - mae: 49746.9336 - val_loss: 50256.2422 - val_mae: 50256.2422
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49730.2422 - mae: 49730.2422 - val_loss: 50254.5469 - val_mae: 50254.5469
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49712.8828 - mae: 49712.8828 - val_loss: 50241.5781 - val_mae: 50241.5781
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49698.1680 - mae: 49698.1680 - val_loss: 50246.0508 - val_mae: 50246.0508
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49686.8008 - mae: 49686.8008 - val_loss: 50236.9609 - val_mae: 50236.9609
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49669.7188 - mae: 49669.7188 - val_loss: 50239.0625 - val_mae: 50239.0625
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49658.1992 - mae: 49658.1992 - val_loss: 50234.6367 - val_mae: 50234.6367
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49645.3828 - mae: 49645.3828 - val_loss: 50229.1875 - val_mae: 50229.1875
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49635.0898 - mae: 49635.0898 - val_loss: 50234.6523 - val_mae: 50234.6523
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49626.5000 - mae: 49626.5000 - val_loss: 50239.0273 - val_mae: 50239.0273
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49613.8672 - mae: 49613.8672 - val_loss: 50235.4766 - val_mae: 50235.4766
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49600.8516 - mae: 49600.8516 - val_loss: 50234.3672 - val_mae: 50234.3672
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49591.1172 - mae: 49591.1172 - val_loss: 50226.7188 - val_mae: 50226.7188
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49583.2461 - mae: 49583.2461 - val_loss: 50225.3477 - val_mae: 50225.3477
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49570.6914 - mae: 49570.6914 - val_loss: 50226.9062 - val_mae: 50226.9062
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49562.5703 - mae: 49562.5703 - val_loss: 50230.0039 - val_mae: 50230.0039
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49553.7148 - mae: 49553.7148 - val_loss: 50234.0859 - val_mae: 50234.0859
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49545.8516 - mae: 49545.8516 - val_loss: 50234.7891 - val_mae: 50234.7891
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49537.5352 - mae: 49537.5352 - val_loss: 50235.9570 - val_mae: 50235.9570

In [20]:
%load_ext tensorboard

In [27]:
%tensorboard --logdir regressionlogs/fit

ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.

In [28]:
# Evaluate the model on test data
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test MAE: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50225.3477 - mae: 50225.3477
Test MAE: 50225.34765625

In [29]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.